<!--
 * @Author: your name
 * @Date: 2020-12-11 15:22:52
 * @LastEditTime: 2020-12-22 14:07:19
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /draw-image-editor/src/App.vue
-->

<template>
	<div id="app">
		<button @click="handleToggle">切换</button>
		<fabricCanvas
			:currentType="currentType"
			@initFabricCanvas="init"
			@savesuccess="savesuccess"
		/>
	</div>
</template>

<script>
	export default {
		name: "App",
		data() {
			return {
				canvasArr: [
					{
						version: "4.2.0",
						objects: [
							{
								type: "ArrowLine",
								version: "4.2.0",
								originX: "left",
								originY: "top",
								left: 87,
								top: 148,
								width: 39,
								height: 71,
								fill: "rgb(0,0,0)",
								stroke: "#ff1e10",
								strokeWidth: 3,
								strokeDashArray: null,
								strokeLineCap: "butt",
								strokeDashOffset: 0,
								strokeLineJoin: "miter",
								strokeMiterLimit: 4,
								scaleX: 1,
								scaleY: 1,
								angle: 0,
								flipX: false,
								flipY: false,
								opacity: 1,
								shadow: null,
								visible: true,
								backgroundColor: "",
								fillRule: "nonzero",
								paintFirst: "fill",
								globalCompositeOperation: "source-over",
								skewX: 0,
								skewY: 0,
								x1: 19.5,
								x2: -19.5,
								y1: -35.5,
								y2: 35.5,
							},
							{
								type: "ArrowLine",
								version: "4.2.0",
								originX: "left",
								originY: "top",
								left: 69,
								top: 76,
								width: 111,
								height: 3,
								fill: "rgb(0,0,0)",
								stroke: "#ff1e10",
								strokeWidth: 3,
								strokeDashArray: null,
								strokeLineCap: "butt",
								strokeDashOffset: 0,
								strokeLineJoin: "miter",
								strokeMiterLimit: 4,
								scaleX: 1,
								scaleY: 1,
								angle: 0,
								flipX: false,
								flipY: false,
								opacity: 1,
								shadow: null,
								visible: true,
								backgroundColor: "",
								fillRule: "nonzero",
								paintFirst: "fill",
								globalCompositeOperation: "source-over",
								skewX: 0,
								skewY: 0,
								x1: -55.5,
								x2: 55.5,
								y1: 1.5,
								y2: -1.5,
							},
						],
						background: "#000",
						width: 300,
						height: 300,
					},
					{
						version: "4.2.0",
						objects: [
							{
								type: "ArrowLine",
								version: "4.2.0",
								originX: "left",
								originY: "top",
								left: 266,
								top: 229,
								width: 27,
								height: 100,
								fill: "rgb(0,0,0)",
								stroke: "#ff1e10",
								strokeWidth: 3,
								strokeDashArray: null,
								strokeLineCap: "butt",
								strokeDashOffset: 0,
								strokeLineJoin: "miter",
								strokeMiterLimit: 4,
								scaleX: 1,
								scaleY: 1,
								angle: 0,
								flipX: false,
								flipY: false,
								opacity: 1,
								shadow: null,
								visible: true,
								backgroundColor: "",
								fillRule: "nonzero",
								paintFirst: "fill",
								globalCompositeOperation: "source-over",
								skewX: 0,
								skewY: 0,
								x1: -13.5,
								x2: 13.5,
								y1: -50,
								y2: 50,
							},
						],
						background: "rgba(0,0,0,0.1)",
						width: 700,
						height: 400,
					},
					{
						version: "4.2.0",
						objects: [
							{
								type: "ArrowLine",
								version: "4.2.0",
								originX: "left",
								originY: "top",
								left: 581,
								top: 114,
								width: 234,
								height: 164,
								fill: "rgb(0,0,0)",
								stroke: "#ff1e10",
								strokeWidth: 3,
								strokeDashArray: null,
								strokeLineCap: "butt",
								strokeDashOffset: 0,
								strokeLineJoin: "miter",
								strokeMiterLimit: 4,
								scaleX: 1,
								scaleY: 1,
								angle: 0,
								flipX: false,
								flipY: false,
								opacity: 1,
								shadow: null,
								visible: true,
								backgroundColor: "",
								fillRule: "nonzero",
								paintFirst: "fill",
								globalCompositeOperation: "source-over",
								skewX: 0,
								skewY: 0,
								x1: 117,
								x2: -117,
								y1: -82,
								y2: 82,
							},
							{
								type: "ArrowLine",
								version: "4.2.0",
								originX: "left",
								originY: "top",
								left: 139,
								top: 186,
								width: 91,
								height: 196,
								fill: "rgb(0,0,0)",
								stroke: "#ff1e10",
								strokeWidth: 3,
								strokeDashArray: null,
								strokeLineCap: "butt",
								strokeDashOffset: 0,
								strokeLineJoin: "miter",
								strokeMiterLimit: 4,
								scaleX: 1,
								scaleY: 1,
								angle: 0,
								flipX: false,
								flipY: false,
								opacity: 1,
								shadow: null,
								visible: true,
								backgroundColor: "",
								fillRule: "nonzero",
								paintFirst: "fill",
								globalCompositeOperation: "source-over",
								skewX: 0,
								skewY: 0,
								x1: -45.5,
								x2: 45.5,
								y1: -98,
								y2: 98,
							},
							{
								type: "line",
								version: "4.2.0",
								originX: "left",
								originY: "top",
								left: 268,
								top: 409,
								width: 500,
								height: 140,
								fill: "rgb(0,0,0)",
								stroke: "rgba(255,30,16,0.2)",
								strokeWidth: 30,
								strokeDashArray: null,
								strokeLineCap: "butt",
								strokeDashOffset: 0,
								strokeLineJoin: "miter",
								strokeMiterLimit: 4,
								scaleX: 1,
								scaleY: 1,
								angle: 0,
								flipX: false,
								flipY: false,
								opacity: 1,
								shadow: null,
								visible: true,
								backgroundColor: "",
								fillRule: "nonzero",
								paintFirst: "fill",
								globalCompositeOperation: "source-over",
								skewX: 0,
								skewY: 0,
								x1: 250,
								x2: -250,
								y1: -70,
								y2: 70,
							},
						],
						background: "#000",
						backgroundImage: {
							type: "image",
							version: "4.2.0",
							originX: "left",
							originY: "top",
							left: 0,
							top: 0,
							width: 1440,
							height: 1080,
							fill: "rgb(0,0,0)",
							stroke: null,
							strokeWidth: 0,
							strokeDashArray: null,
							strokeLineCap: "butt",
							strokeDashOffset: 0,
							strokeLineJoin: "miter",
							strokeMiterLimit: 4,
							scaleX: 0.69,
							scaleY: 0.69,
							angle: 0,
							flipX: false,
							flipY: false,
							opacity: 1,
							shadow: null,
							visible: true,
							backgroundColor: "",
							fillRule: "nonzero",
							paintFirst: "fill",
							globalCompositeOperation: "source-over",
							skewX: 0,
							skewY: 0,
							cropX: 0,
							cropY: 0,
							src:
								"https://img.zhugexuetang.com/B4C3778D-6461-D1FD-8DF5-91B0FF705F53.jpg",
							crossOrigin: "anonymous",
							filters: [],
						},
						width: 993.5999999999999,
						height: 745.1999999999999,
					},
				],
				url: "",
				index: 0,
				maxWidth: 1000,
				FabricEl: null,
				currentType: {
					name: "arrow",
					color: "red",
					size: "normal",
				},
			};
		},
		methods: {
			init(InitFabric) {
				var data = (this.url = this.canvasArr[0]);
				const opt = {
					canvasData: data, // 渲染数据
				};
				this.FabricEl = new InitFabric(opt);
				console.log("this.FabricEl", this.FabricEl);
			},
			handleToggle() {
				this.index =
					this.index >= this.canvasArr.length - 1
						? 0
						: this.index + 1;
				this.url = this.canvasArr[this.index];
				var result = this.FabricEl.toCanvasJSON();
				console.log(this.url);
				this.currentType = {
					name: "wave",
					color: "yellow",
					size: "big",
				};
				this.FabricEl.refreshImageCanvas({ canvasData: this.url });
			},
			savesuccess(file) {
				console.log(JSON.stringify(file));
			},
		},
	};
</script>
